# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_topic_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(help_text='Tanga igitekerezo aha', max_length=4000),
        ),
    ]
